@startuml Ecopoints
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

SHOW_PERSON_PORTRAIT()
LAYOUT_LEFT_RIGHT()

title Diagrama de Conteiner BURI

AddElementTag("1", $bgColor="Green", $borderColor="DarkGreen", $fontColor="White")

Person(user_app, "Cliente" ,"Usuário doméstico", $tags="1")

Enterprise_Boundary(buri_system,"Sistema BURI"){
    Container(equipment,"Dispositivo Eletrônico","microcontrolador Esp32 com os sensores DHT11 e MQ7", $tags="1")
    Container(server,"Servidor","API de coleta de dados e envio de alerta sobre o ambiente", $tags="1")
    Container(app,"Aplicativo","Responsável por mostrar os dados em tempo real do dispositivo e realizar configuração do equipamento", $tags="1")
    ContainerDb(db, "Banco de Dados", "Postgresql 14", $tags="1")
}

Rel(server, db, "Consulta e escreve os dados no")
Rel(db, server, "Pega os dados do")
Rel(app,server,"solicita medições em tempo real")
Rel(equipment,server,"Envia dados dos sensores para o")
Rel(app,equipment,"configura e dar manutenção no")
Rel(server,app,"envia alerta de risco")
Rel(user_app,app,"Utiliza o")
Rel(user_app,equipment,"Configura e utiliza o")


@enduml