spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000