version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buri-api
    image: buri-api:1.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - buridb
    networks:
      - buri-network

  buridb:
    image: postgres:14
    container_name: buri-db
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - buri-postgres-data:/var/lib/postgresql/data
    networks:
      - buri-network
volumes:
  buri-postgres-data:
    driver: local

networks:
  buri-network:
    driver: bridge
